.PHONY: icons

icons:
	2goarray Available icons < icons/available.ico > icons/available.go
	2goarray Partially icons < icons/partially.ico > icons/partially.go
	2goarray Unavailable icons < icons/unavailable.ico > icons/unavailable.go
	2goarray Tractor icons < icons/tractor.ico > icons/tractor.go