.PHONY: icons

icons:
	2goarray Available icons < icons/available.png > icons/available.go
	2goarray Partially icons < icons/partially.png > icons/partially.go
	2goarray Unavailable icons < icons/unavailable.png > icons/unavailable.go
	2goarray Tractor icons < icons/tractor.png > icons/tractor.go